/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.3.0 (NJsonSchema v10.0.27.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { DlmtApiUrl } from 'src/app/common/config/app-config';

//export const DlmtApiUrl = new InjectionToken<string>('DlmtApiUrl');

@Injectable()
export class CaseTypeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(DlmtApiUrl) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    all(body: CaseTypeGetAllRequest | undefined): Observable<CaseTypeGetAllResponse> {
        let url_ = this.baseUrl + "/api/CaseType/fetch/all";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json", 
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAll(<any>response_);
                } catch (e) {
                    return <Observable<CaseTypeGetAllResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<CaseTypeGetAllResponse>><any>_observableThrow(response_);
        }));
    }

    protected processAll(response: HttpResponseBase): Observable<CaseTypeGetAllResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CaseTypeGetAllResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400) {
                result400 = {} as any;
                for (let key in resultData400) {
                    if (resultData400.hasOwnProperty(key))
                        result400![key] = resultData400[key];
                }
            }
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CaseTypeGetAllResponse>(<any>null);
    }

    /**
     * @return Success
     */
    fetch(id: number): Observable<CaseTypeGetByIdResponse> {
        let url_ = this.baseUrl + "/api/CaseType/fetch/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processFetch(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processFetch(<any>response_);
                } catch (e) {
                    return <Observable<CaseTypeGetByIdResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<CaseTypeGetByIdResponse>><any>_observableThrow(response_);
        }));
    }

    protected processFetch(response: HttpResponseBase): Observable<CaseTypeGetByIdResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CaseTypeGetByIdResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400) {
                result400 = {} as any;
                for (let key in resultData400) {
                    if (resultData400.hasOwnProperty(key))
                        result400![key] = resultData400[key];
                }
            }
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CaseTypeGetByIdResponse>(<any>null);
    }

    /**
     * @return Success
     */
    delete(id: number): Observable<CaseTypeDeleteByIdResponse> {
        let url_ = this.baseUrl + "/api/CaseType/delete/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDelete(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDelete(<any>response_);
                } catch (e) {
                    return <Observable<CaseTypeDeleteByIdResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<CaseTypeDeleteByIdResponse>><any>_observableThrow(response_);
        }));
    }

    protected processDelete(response: HttpResponseBase): Observable<CaseTypeDeleteByIdResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CaseTypeDeleteByIdResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400) {
                result400 = {} as any;
                for (let key in resultData400) {
                    if (resultData400.hasOwnProperty(key))
                        result400![key] = resultData400[key];
                }
            }
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CaseTypeDeleteByIdResponse>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    update(body: CaseTypeUpdateRequest | undefined): Observable<CaseTypeUpdateResponse> {
        let url_ = this.baseUrl + "/api/CaseType/Update";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json", 
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdate(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdate(<any>response_);
                } catch (e) {
                    return <Observable<CaseTypeUpdateResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<CaseTypeUpdateResponse>><any>_observableThrow(response_);
        }));
    }

    protected processUpdate(response: HttpResponseBase): Observable<CaseTypeUpdateResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CaseTypeUpdateResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400) {
                result400 = {} as any;
                for (let key in resultData400) {
                    if (resultData400.hasOwnProperty(key))
                        result400![key] = resultData400[key];
                }
            }
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CaseTypeUpdateResponse>(<any>null);
    }
}

@Injectable()
export class PlanningOfficeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(DlmtApiUrl) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    all(body: PlanningOfficeGetAllRequest | undefined): Observable<PlanningOfficeGetAllResponse> {
        let url_ = this.baseUrl + "/api/PlanningOffice/fetch/all";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json", 
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAll(<any>response_);
                } catch (e) {
                    return <Observable<PlanningOfficeGetAllResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<PlanningOfficeGetAllResponse>><any>_observableThrow(response_);
        }));
    }

    protected processAll(response: HttpResponseBase): Observable<PlanningOfficeGetAllResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PlanningOfficeGetAllResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400) {
                result400 = {} as any;
                for (let key in resultData400) {
                    if (resultData400.hasOwnProperty(key))
                        result400![key] = resultData400[key];
                }
            }
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PlanningOfficeGetAllResponse>(<any>null);
    }
}

export class FilterCondition implements IFilterCondition {
    filterType?: string | undefined;
    searchKey?: string | undefined;

    constructor(data?: IFilterCondition) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.filterType = _data["filterType"];
            this.searchKey = _data["searchKey"];
        }
    }

    static fromJS(data: any): FilterCondition {
        data = typeof data === 'object' ? data : {};
        let result = new FilterCondition();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["filterType"] = this.filterType;
        data["searchKey"] = this.searchKey;
        return data; 
    }
}

export interface IFilterCondition {
    filterType?: string | undefined;
    searchKey?: string | undefined;
}

export class FilterQuery implements IFilterQuery {
    filterOperator?: string | undefined;
    columnName?: string | undefined;
    dataType?: string | undefined;
    conditions?: FilterCondition[] | undefined;

    constructor(data?: IFilterQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.filterOperator = _data["filterOperator"];
            this.columnName = _data["columnName"];
            this.dataType = _data["dataType"];
            if (Array.isArray(_data["conditions"])) {
                this.conditions = [] as any;
                for (let item of _data["conditions"])
                    this.conditions!.push(FilterCondition.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FilterQuery {
        data = typeof data === 'object' ? data : {};
        let result = new FilterQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["filterOperator"] = this.filterOperator;
        data["columnName"] = this.columnName;
        data["dataType"] = this.dataType;
        if (Array.isArray(this.conditions)) {
            data["conditions"] = [];
            for (let item of this.conditions)
                data["conditions"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IFilterQuery {
    filterOperator?: string | undefined;
    columnName?: string | undefined;
    dataType?: string | undefined;
    conditions?: FilterCondition[] | undefined;
}

export class FilterModel implements IFilterModel {
    filterQueries?: FilterQuery[] | undefined;

    constructor(data?: IFilterModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["filterQueries"])) {
                this.filterQueries = [] as any;
                for (let item of _data["filterQueries"])
                    this.filterQueries!.push(FilterQuery.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FilterModel {
        data = typeof data === 'object' ? data : {};
        let result = new FilterModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.filterQueries)) {
            data["filterQueries"] = [];
            for (let item of this.filterQueries)
                data["filterQueries"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IFilterModel {
    filterQueries?: FilterQuery[] | undefined;
}

export class SortCondition implements ISortCondition {
    columnName?: string | undefined;
    sortType?: string | undefined;

    constructor(data?: ISortCondition) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.columnName = _data["columnName"];
            this.sortType = _data["sortType"];
        }
    }

    static fromJS(data: any): SortCondition {
        data = typeof data === 'object' ? data : {};
        let result = new SortCondition();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["columnName"] = this.columnName;
        data["sortType"] = this.sortType;
        return data; 
    }
}

export interface ISortCondition {
    columnName?: string | undefined;
    sortType?: string | undefined;
}

export class SortModel implements ISortModel {
    sortConditions?: SortCondition[] | undefined;

    constructor(data?: ISortModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["sortConditions"])) {
                this.sortConditions = [] as any;
                for (let item of _data["sortConditions"])
                    this.sortConditions!.push(SortCondition.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SortModel {
        data = typeof data === 'object' ? data : {};
        let result = new SortModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.sortConditions)) {
            data["sortConditions"] = [];
            for (let item of this.sortConditions)
                data["sortConditions"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ISortModel {
    sortConditions?: SortCondition[] | undefined;
}

export class ViewPredicate implements IViewPredicate {
    startRow?: number;
    endRow?: number;
    filter?: FilterModel;
    sort?: SortModel;

    constructor(data?: IViewPredicate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.startRow = _data["startRow"];
            this.endRow = _data["endRow"];
            this.filter = _data["filter"] ? FilterModel.fromJS(_data["filter"]) : <any>undefined;
            this.sort = _data["sort"] ? SortModel.fromJS(_data["sort"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ViewPredicate {
        data = typeof data === 'object' ? data : {};
        let result = new ViewPredicate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["startRow"] = this.startRow;
        data["endRow"] = this.endRow;
        data["filter"] = this.filter ? this.filter.toJSON() : <any>undefined;
        data["sort"] = this.sort ? this.sort.toJSON() : <any>undefined;
        return data; 
    }
}

export interface IViewPredicate {
    startRow?: number;
    endRow?: number;
    filter?: FilterModel;
    sort?: SortModel;
}

export class CaseTypeGetAllRequest implements ICaseTypeGetAllRequest {
    predicate?: ViewPredicate;
    currentUser?: string | undefined;
    roles?: string[] | undefined;

    constructor(data?: ICaseTypeGetAllRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.predicate = _data["predicate"] ? ViewPredicate.fromJS(_data["predicate"]) : <any>undefined;
            this.currentUser = _data["currentUser"];
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(item);
            }
        }
    }

    static fromJS(data: any): CaseTypeGetAllRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeGetAllRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["predicate"] = this.predicate ? this.predicate.toJSON() : <any>undefined;
        data["currentUser"] = this.currentUser;
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item);
        }
        return data; 
    }
}

export interface ICaseTypeGetAllRequest {
    predicate?: ViewPredicate;
    currentUser?: string | undefined;
    roles?: string[] | undefined;
}

export class CaseTypeDTO implements ICaseTypeDTO {
    id?: number;
    caseType?: string | undefined;
    description?: string | undefined;
    createdBy?: string | undefined;
    createdDate?: Date;
    updatedDate?: Date;
    updatedBy?: string | undefined;
    statusId?: number;

    constructor(data?: ICaseTypeDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.caseType = _data["caseType"];
            this.description = _data["description"];
            this.createdBy = _data["createdBy"];
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : <any>undefined;
            this.updatedDate = _data["updatedDate"] ? new Date(_data["updatedDate"].toString()) : <any>undefined;
            this.updatedBy = _data["updatedBy"];
            this.statusId = _data["statusId"];
        }
    }

    static fromJS(data: any): CaseTypeDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["caseType"] = this.caseType;
        data["description"] = this.description;
        data["createdBy"] = this.createdBy;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : <any>undefined;
        data["updatedDate"] = this.updatedDate ? this.updatedDate.toISOString() : <any>undefined;
        data["updatedBy"] = this.updatedBy;
        data["statusId"] = this.statusId;
        return data; 
    }
}

export interface ICaseTypeDTO {
    id?: number;
    caseType?: string | undefined;
    description?: string | undefined;
    createdBy?: string | undefined;
    createdDate?: Date;
    updatedDate?: Date;
    updatedBy?: string | undefined;
    statusId?: number;
}

export class ErrorDTO implements IErrorDTO {
    errorCode?: string | undefined;
    errorType?: string | undefined;
    errorMsg?: string | undefined;

    constructor(data?: IErrorDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.errorCode = _data["errorCode"];
            this.errorType = _data["errorType"];
            this.errorMsg = _data["errorMsg"];
        }
    }

    static fromJS(data: any): ErrorDTO {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["errorCode"] = this.errorCode;
        data["errorType"] = this.errorType;
        data["errorMsg"] = this.errorMsg;
        return data; 
    }
}

export interface IErrorDTO {
    errorCode?: string | undefined;
    errorType?: string | undefined;
    errorMsg?: string | undefined;
}

export class CaseTypeGetAllResponse implements ICaseTypeGetAllResponse {
    result?: CaseTypeDTO[] | undefined;
    total?: number;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;

    constructor(data?: ICaseTypeGetAllResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["result"])) {
                this.result = [] as any;
                for (let item of _data["result"])
                    this.result!.push(CaseTypeDTO.fromJS(item));
            }
            this.total = _data["total"];
            this.hasError = _data["hasError"];
            if (Array.isArray(_data["errorMsgs"])) {
                this.errorMsgs = [] as any;
                for (let item of _data["errorMsgs"])
                    this.errorMsgs!.push(ErrorDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CaseTypeGetAllResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeGetAllResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.result)) {
            data["result"] = [];
            for (let item of this.result)
                data["result"].push(item.toJSON());
        }
        data["total"] = this.total;
        data["hasError"] = this.hasError;
        if (Array.isArray(this.errorMsgs)) {
            data["errorMsgs"] = [];
            for (let item of this.errorMsgs)
                data["errorMsgs"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICaseTypeGetAllResponse {
    result?: CaseTypeDTO[] | undefined;
    total?: number;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;
}

export class CaseTypeGetByIdResponse implements ICaseTypeGetByIdResponse {
    data?: CaseTypeDTO;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;

    constructor(data?: ICaseTypeGetByIdResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["data"] ? CaseTypeDTO.fromJS(_data["data"]) : <any>undefined;
            this.hasError = _data["hasError"];
            if (Array.isArray(_data["errorMsgs"])) {
                this.errorMsgs = [] as any;
                for (let item of _data["errorMsgs"])
                    this.errorMsgs!.push(ErrorDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CaseTypeGetByIdResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeGetByIdResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        data["hasError"] = this.hasError;
        if (Array.isArray(this.errorMsgs)) {
            data["errorMsgs"] = [];
            for (let item of this.errorMsgs)
                data["errorMsgs"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICaseTypeGetByIdResponse {
    data?: CaseTypeDTO;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;
}

export class CaseTypeDeleteByIdResponse implements ICaseTypeDeleteByIdResponse {
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;

    constructor(data?: ICaseTypeDeleteByIdResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.hasError = _data["hasError"];
            if (Array.isArray(_data["errorMsgs"])) {
                this.errorMsgs = [] as any;
                for (let item of _data["errorMsgs"])
                    this.errorMsgs!.push(ErrorDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CaseTypeDeleteByIdResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeDeleteByIdResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["hasError"] = this.hasError;
        if (Array.isArray(this.errorMsgs)) {
            data["errorMsgs"] = [];
            for (let item of this.errorMsgs)
                data["errorMsgs"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICaseTypeDeleteByIdResponse {
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;
}

export class CaseTypeUpdateRequest implements ICaseTypeUpdateRequest {
    caseType?: CaseTypeDTO;
    currentUser?: string | undefined;
    roles?: string[] | undefined;

    constructor(data?: ICaseTypeUpdateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.caseType = _data["caseType"] ? CaseTypeDTO.fromJS(_data["caseType"]) : <any>undefined;
            this.currentUser = _data["currentUser"];
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(item);
            }
        }
    }

    static fromJS(data: any): CaseTypeUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["caseType"] = this.caseType ? this.caseType.toJSON() : <any>undefined;
        data["currentUser"] = this.currentUser;
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item);
        }
        return data; 
    }
}

export interface ICaseTypeUpdateRequest {
    caseType?: CaseTypeDTO;
    currentUser?: string | undefined;
    roles?: string[] | undefined;
}

export class CaseTypeUpdateResponse implements ICaseTypeUpdateResponse {
    data?: CaseTypeDTO;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;

    constructor(data?: ICaseTypeUpdateResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["data"] ? CaseTypeDTO.fromJS(_data["data"]) : <any>undefined;
            this.hasError = _data["hasError"];
            if (Array.isArray(_data["errorMsgs"])) {
                this.errorMsgs = [] as any;
                for (let item of _data["errorMsgs"])
                    this.errorMsgs!.push(ErrorDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CaseTypeUpdateResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CaseTypeUpdateResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        data["hasError"] = this.hasError;
        if (Array.isArray(this.errorMsgs)) {
            data["errorMsgs"] = [];
            for (let item of this.errorMsgs)
                data["errorMsgs"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICaseTypeUpdateResponse {
    data?: CaseTypeDTO;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;
}

export class PlanningOfficeGetAllRequest implements IPlanningOfficeGetAllRequest {
    predicate?: ViewPredicate;
    currentUser?: string | undefined;
    roles?: string[] | undefined;

    constructor(data?: IPlanningOfficeGetAllRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.predicate = _data["predicate"] ? ViewPredicate.fromJS(_data["predicate"]) : <any>undefined;
            this.currentUser = _data["currentUser"];
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(item);
            }
        }
    }

    static fromJS(data: any): PlanningOfficeGetAllRequest {
        data = typeof data === 'object' ? data : {};
        let result = new PlanningOfficeGetAllRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["predicate"] = this.predicate ? this.predicate.toJSON() : <any>undefined;
        data["currentUser"] = this.currentUser;
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item);
        }
        return data; 
    }
}

export interface IPlanningOfficeGetAllRequest {
    predicate?: ViewPredicate;
    currentUser?: string | undefined;
    roles?: string[] | undefined;
}

export class PlanningOfficeDTO implements IPlanningOfficeDTO {
    id?: number;
    name?: string | undefined;
    createdBy?: string | undefined;
    createdDate?: Date;
    updatedDate?: Date;
    updatedBy?: string | undefined;
    statusId?: number;

    constructor(data?: IPlanningOfficeDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.createdBy = _data["createdBy"];
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : <any>undefined;
            this.updatedDate = _data["updatedDate"] ? new Date(_data["updatedDate"].toString()) : <any>undefined;
            this.updatedBy = _data["updatedBy"];
            this.statusId = _data["statusId"];
        }
    }

    static fromJS(data: any): PlanningOfficeDTO {
        data = typeof data === 'object' ? data : {};
        let result = new PlanningOfficeDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["createdBy"] = this.createdBy;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : <any>undefined;
        data["updatedDate"] = this.updatedDate ? this.updatedDate.toISOString() : <any>undefined;
        data["updatedBy"] = this.updatedBy;
        data["statusId"] = this.statusId;
        return data; 
    }
}

export interface IPlanningOfficeDTO {
    id?: number;
    name?: string | undefined;
    createdBy?: string | undefined;
    createdDate?: Date;
    updatedDate?: Date;
    updatedBy?: string | undefined;
    statusId?: number;
}

export class PlanningOfficeGetAllResponse implements IPlanningOfficeGetAllResponse {
    result?: PlanningOfficeDTO[] | undefined;
    total?: number;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;

    constructor(data?: IPlanningOfficeGetAllResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["result"])) {
                this.result = [] as any;
                for (let item of _data["result"])
                    this.result!.push(PlanningOfficeDTO.fromJS(item));
            }
            this.total = _data["total"];
            this.hasError = _data["hasError"];
            if (Array.isArray(_data["errorMsgs"])) {
                this.errorMsgs = [] as any;
                for (let item of _data["errorMsgs"])
                    this.errorMsgs!.push(ErrorDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PlanningOfficeGetAllResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PlanningOfficeGetAllResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.result)) {
            data["result"] = [];
            for (let item of this.result)
                data["result"].push(item.toJSON());
        }
        data["total"] = this.total;
        data["hasError"] = this.hasError;
        if (Array.isArray(this.errorMsgs)) {
            data["errorMsgs"] = [];
            for (let item of this.errorMsgs)
                data["errorMsgs"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IPlanningOfficeGetAllResponse {
    result?: PlanningOfficeDTO[] | undefined;
    total?: number;
    hasError?: boolean;
    errorMsgs?: ErrorDTO[] | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}